stages:
  - build
  - test
  - deploy_dev
  - deploy
  - cleanup


build:
  stage: build
  script:
    - docker build -t $CI_PROJECT_NAME .
  only:
    - dev
    - master
  allow_failure: false

testing:
  stage: test
  script:
    - echo "Testing"
  only:
    - dev

deploy_to_dev:
  stage: deploy_dev
  script:
    - docker-compose -f docker-compose.yml up -d
  only:
    - dev

deploy_to_prod:
  stage: deploy
  script:
    - docker-compose -f docker-compose-prod.yml up -d
  only:
    - master
  # when: manual

cleanup:
  stage: cleanup
  when: always
  script:
    - echo "Stop & remove containers"
